$(function () {
	Load();
});	

function Load()
{
	SeteoVariablesGlobales();
	document.getElementById("rbtn1").checked = 1;
	PracticarUnoNuevo();
}
function SeteoVariablesGlobales()
{
	//document.getElementById("lblResultado").style.visibility = "hidden";
	//$("#lblEstado").text("0/1");
palabra = { PalabraIngles:"	accept	", PalabraNativa:"	Accepter  	", PalabraTraducida:"	aceptar	"}; unasPalabras[	0	] = palabra;
palabra = { PalabraIngles:"	achieve	", PalabraNativa:"	Réussir  	", PalabraTraducida:"	lograr	"}; unasPalabras[	1	] = palabra;
palabra = { PalabraIngles:"	add	", PalabraNativa:"	Ajouter  	", PalabraTraducida:"	agregar	"}; unasPalabras[	2	] = palabra;
palabra = { PalabraIngles:"	admire	", PalabraNativa:"	Admirer  	", PalabraTraducida:"	admirar	"}; unasPalabras[	3	] = palabra;
palabra = { PalabraIngles:"	admit	", PalabraNativa:"	Admettre  	", PalabraTraducida:"	admitir	"}; unasPalabras[	4	] = palabra;
palabra = { PalabraIngles:"	advise	", PalabraNativa:"	Conseiller  	", PalabraTraducida:"	aconsejar	"}; unasPalabras[	5	] = palabra;
palabra = { PalabraIngles:"	afford	", PalabraNativa:"	Pouvoir se permettre  	", PalabraTraducida:"	poder pagar	"}; unasPalabras[	6	] = palabra;
palabra = { PalabraIngles:"	agree	", PalabraNativa:"	Accepter  	", PalabraTraducida:"	aceptar	"}; unasPalabras[	7	] = palabra;
palabra = { PalabraIngles:"	allow	", PalabraNativa:"	Permettre  	", PalabraTraducida:"	permitir	"}; unasPalabras[	8	] = palabra;
palabra = { PalabraIngles:"	announce	", PalabraNativa:"	Annoncer  	", PalabraTraducida:"	anunciar	"}; unasPalabras[	9	] = palabra;
palabra = { PalabraIngles:"	answer	", PalabraNativa:"	Réponse  	", PalabraTraducida:"	respuesta	"}; unasPalabras[	10	] = palabra;
palabra = { PalabraIngles:"	appear	", PalabraNativa:"	Apparaître  	", PalabraTraducida:"	aparecer	"}; unasPalabras[	11	] = palabra;
palabra = { PalabraIngles:"	apply	", PalabraNativa:"	Postuler  	", PalabraTraducida:"	aplicar	"}; unasPalabras[	12	] = palabra;
palabra = { PalabraIngles:"	argue	", PalabraNativa:"	Argumenter  	", PalabraTraducida:"	argumentar	"}; unasPalabras[	13	] = palabra;
palabra = { PalabraIngles:"	arrange	", PalabraNativa:"	Réparer  	", PalabraTraducida:"	arreglar	"}; unasPalabras[	14	] = palabra;
palabra = { PalabraIngles:"	arrive	", PalabraNativa:"	Arriver  	", PalabraTraducida:"	llegar	"}; unasPalabras[	15	] = palabra;
palabra = { PalabraIngles:"	ask	", PalabraNativa:"	Demander  	", PalabraTraducida:"	preguntar	"}; unasPalabras[	16	] = palabra;
palabra = { PalabraIngles:"	avoid	", PalabraNativa:"	Éviter  	", PalabraTraducida:"	evitar	"}; unasPalabras[	17	] = palabra;
palabra = { PalabraIngles:"	bake	", PalabraNativa:"	Cuire  	", PalabraTraducida:"	hornear	"}; unasPalabras[	18	] = palabra;
palabra = { PalabraIngles:"	bathe	", PalabraNativa:"	Se baigner  	", PalabraTraducida:"	bañarse	"}; unasPalabras[	19	] = palabra;
palabra = { PalabraIngles:"	become	", PalabraNativa:"	Devenir  	", PalabraTraducida:"	convertirse	"}; unasPalabras[	20	] = palabra;
palabra = { PalabraIngles:"	begin	", PalabraNativa:"	Commencer  	", PalabraTraducida:"	comenzar	"}; unasPalabras[	21	] = palabra;
palabra = { PalabraIngles:"	behave	", PalabraNativa:"	Se comporter  	", PalabraTraducida:"	comportarse	"}; unasPalabras[	22	] = palabra;
palabra = { PalabraIngles:"	believe	", PalabraNativa:"	Croire  	", PalabraTraducida:"	creer	"}; unasPalabras[	23	] = palabra;
palabra = { PalabraIngles:"	belong	", PalabraNativa:"	Appartenir  	", PalabraTraducida:"	pertenecer	"}; unasPalabras[	24	] = palabra;
palabra = { PalabraIngles:"	borrow	", PalabraNativa:"	Emprunter  	", PalabraTraducida:"	pedir prestado	"}; unasPalabras[	25	] = palabra;
palabra = { PalabraIngles:"	break	", PalabraNativa:"	Casser  	", PalabraTraducida:"	romper	"}; unasPalabras[	26	] = palabra;
palabra = { PalabraIngles:"	bring	", PalabraNativa:"	Apporter  	", PalabraTraducida:"	traer	"}; unasPalabras[	27	] = palabra;
palabra = { PalabraIngles:"	build	", PalabraNativa:"	Construire  	", PalabraTraducida:"	construir	"}; unasPalabras[	28	] = palabra;
palabra = { PalabraIngles:"	buy	", PalabraNativa:"	Acheter  	", PalabraTraducida:"	comprar	"}; unasPalabras[	29	] = palabra;
palabra = { PalabraIngles:"	call	", PalabraNativa:"	Appeler  	", PalabraTraducida:"	llamar	"}; unasPalabras[	30	] = palabra;
palabra = { PalabraIngles:"	cancel	", PalabraNativa:"	Annuler  	", PalabraTraducida:"	cancelar	"}; unasPalabras[	31	] = palabra;
palabra = { PalabraIngles:"	care	", PalabraNativa:"	Attention  	", PalabraTraducida:"	cuidado	"}; unasPalabras[	32	] = palabra;
palabra = { PalabraIngles:"	carry	", PalabraNativa:"	Porter  	", PalabraTraducida:"	llevar	"}; unasPalabras[	33	] = palabra;
palabra = { PalabraIngles:"	catch	", PalabraNativa:"	Attraper  	", PalabraTraducida:"	atrapar	"}; unasPalabras[	34	] = palabra;
palabra = { PalabraIngles:"	change	", PalabraNativa:"	Changer  	", PalabraTraducida:"	cambiar	"}; unasPalabras[	35	] = palabra;
palabra = { PalabraIngles:"	check	", PalabraNativa:"	Contrôler  	", PalabraTraducida:"	controlar	"}; unasPalabras[	36	] = palabra;
palabra = { PalabraIngles:"	choose	", PalabraNativa:"	Choisir  	", PalabraTraducida:"	elegir	"}; unasPalabras[	37	] = palabra;
palabra = { PalabraIngles:"	clean	", PalabraNativa:"	Propre  	", PalabraTraducida:"	limpio	"}; unasPalabras[	38	] = palabra;
palabra = { PalabraIngles:"	clear	", PalabraNativa:"	Clair  	", PalabraTraducida:"	claro	"}; unasPalabras[	39	] = palabra;
palabra = { PalabraIngles:"	climb	", PalabraNativa:"	Grimper  	", PalabraTraducida:"	trepar	"}; unasPalabras[	40	] = palabra;
palabra = { PalabraIngles:"	close	", PalabraNativa:"	Fermer  	", PalabraTraducida:"	cerca	"}; unasPalabras[	41	] = palabra;
palabra = { PalabraIngles:"	collect	", PalabraNativa:"	Ramasser  	", PalabraTraducida:"	recolectar	"}; unasPalabras[	42	] = palabra;
palabra = { PalabraIngles:"	come	", PalabraNativa:"	Venir  	", PalabraTraducida:"	venir	"}; unasPalabras[	43	] = palabra;
palabra = { PalabraIngles:"	complain	", PalabraNativa:"	Se plaindre  	", PalabraTraducida:"	quejarse	"}; unasPalabras[	44	] = palabra;
palabra = { PalabraIngles:"	complete	", PalabraNativa:"	Complet  	", PalabraTraducida:"	completo	"}; unasPalabras[	45	] = palabra;
palabra = { PalabraIngles:"	concern	", PalabraNativa:"	Inquiétude  	", PalabraTraducida:"	inquietud	"}; unasPalabras[	46	] = palabra;
palabra = { PalabraIngles:"	confirm	", PalabraNativa:"	Confirmer  	", PalabraTraducida:"	confirmar	"}; unasPalabras[	47	] = palabra;
palabra = { PalabraIngles:"	connect	", PalabraNativa:"	Connecter  	", PalabraTraducida:"	conectar	"}; unasPalabras[	48	] = palabra;
palabra = { PalabraIngles:"	consider	", PalabraNativa:"	Considérer  	", PalabraTraducida:"	considerar	"}; unasPalabras[	49	] = palabra;
palabra = { PalabraIngles:"	contain	", PalabraNativa:"	Contenir  	", PalabraTraducida:"	contener	"}; unasPalabras[	50	] = palabra;
palabra = { PalabraIngles:"	continue	", PalabraNativa:"	Continuer  	", PalabraTraducida:"	continuar	"}; unasPalabras[	51	] = palabra;
palabra = { PalabraIngles:"	cook	", PalabraNativa:"	Cuisiner  	", PalabraTraducida:"	cocinar	"}; unasPalabras[	52	] = palabra;
palabra = { PalabraIngles:"	copy	", PalabraNativa:"	Copier  	", PalabraTraducida:"	copiar	"}; unasPalabras[	53	] = palabra;
palabra = { PalabraIngles:"	correct	", PalabraNativa:"	Correct  	", PalabraTraducida:"	correcto	"}; unasPalabras[	54	] = palabra;
palabra = { PalabraIngles:"	cost	", PalabraNativa:"	Coût  	", PalabraTraducida:"	costo	"}; unasPalabras[	55	] = palabra;
palabra = { PalabraIngles:"	count	", PalabraNativa:"	Compter  	", PalabraTraducida:"	contar	"}; unasPalabras[	56	] = palabra;
palabra = { PalabraIngles:"	cover	", PalabraNativa:"	Couvrir  	", PalabraTraducida:"	cubrir	"}; unasPalabras[	57	] = palabra;
palabra = { PalabraIngles:"	create	", PalabraNativa:"	Créer  	", PalabraTraducida:"	crear	"}; unasPalabras[	58	] = palabra;
palabra = { PalabraIngles:"	cross	", PalabraNativa:"	Croix  	", PalabraTraducida:"	cruz	"}; unasPalabras[	59	] = palabra;
palabra = { PalabraIngles:"	cry	", PalabraNativa:"	Pleurer  	", PalabraTraducida:"	llorar	"}; unasPalabras[	60	] = palabra;
palabra = { PalabraIngles:"	cut	", PalabraNativa:"	Couper  	", PalabraTraducida:"	cortar	"}; unasPalabras[	61	] = palabra;
palabra = { PalabraIngles:"	dance	", PalabraNativa:"	Danser  	", PalabraTraducida:"	bailar	"}; unasPalabras[	62	] = palabra;
palabra = { PalabraIngles:"	decide	", PalabraNativa:"	Décider  	", PalabraTraducida:"	decidir	"}; unasPalabras[	63	] = palabra;
palabra = { PalabraIngles:"	deliver	", PalabraNativa:"	Livrer  	", PalabraTraducida:"	entregar	"}; unasPalabras[	64	] = palabra;
palabra = { PalabraIngles:"	depend	", PalabraNativa:"	Dépendre  	", PalabraTraducida:"	depender	"}; unasPalabras[	65	] = palabra;
palabra = { PalabraIngles:"	describe	", PalabraNativa:"	Décrire  	", PalabraTraducida:"	describir	"}; unasPalabras[	66	] = palabra;
palabra = { PalabraIngles:"	deserve	", PalabraNativa:"	Mériter  	", PalabraTraducida:"	merecer	"}; unasPalabras[	67	] = palabra;
palabra = { PalabraIngles:"	design	", PalabraNativa:"	Conception  	", PalabraTraducida:"	diseño	"}; unasPalabras[	68	] = palabra;
palabra = { PalabraIngles:"	destroy	", PalabraNativa:"	Détruire  	", PalabraTraducida:"	destruir	"}; unasPalabras[	69	] = palabra;
palabra = { PalabraIngles:"	develop	", PalabraNativa:"	Développer  	", PalabraTraducida:"	desarrollar	"}; unasPalabras[	70	] = palabra;
palabra = { PalabraIngles:"	die	", PalabraNativa:"	Mourir  	", PalabraTraducida:"	morir	"}; unasPalabras[	71	] = palabra;
palabra = { PalabraIngles:"	discover	", PalabraNativa:"	Découvrir  	", PalabraTraducida:"	descubrir	"}; unasPalabras[	72	] = palabra;
palabra = { PalabraIngles:"	discuss	", PalabraNativa:"	Discuter  	", PalabraTraducida:"	conversar	"}; unasPalabras[	73	] = palabra;
palabra = { PalabraIngles:"	divide	", PalabraNativa:"	Diviser  	", PalabraTraducida:"	dividir	"}; unasPalabras[	74	] = palabra;
palabra = { PalabraIngles:"	do	", PalabraNativa:"	Faire  	", PalabraTraducida:"	hacer	"}; unasPalabras[	75	] = palabra;
palabra = { PalabraIngles:"	draw	", PalabraNativa:"	Dessiner  	", PalabraTraducida:"	dibujar	"}; unasPalabras[	76	] = palabra;
palabra = { PalabraIngles:"	dress	", PalabraNativa:"	Robe  	", PalabraTraducida:"	vestido	"}; unasPalabras[	77	] = palabra;
palabra = { PalabraIngles:"	drink	", PalabraNativa:"	Boire  	", PalabraTraducida:"	beber	"}; unasPalabras[	78	] = palabra;
palabra = { PalabraIngles:"	drive	", PalabraNativa:"	Conduire  	", PalabraTraducida:"	conducir	"}; unasPalabras[	79	] = palabra;
palabra = { PalabraIngles:"	eat	", PalabraNativa:"	Manger  	", PalabraTraducida:"	comer	"}; unasPalabras[	80	] = palabra;
palabra = { PalabraIngles:"	educate	", PalabraNativa:"	Éduquer  	", PalabraTraducida:"	educar	"}; unasPalabras[	81	] = palabra;
palabra = { PalabraIngles:"	encourage	", PalabraNativa:"	Encourager  	", PalabraTraducida:"	alentar	"}; unasPalabras[	82	] = palabra;
palabra = { PalabraIngles:"	enjoy	", PalabraNativa:"	Profiter  	", PalabraTraducida:"	disfrutar	"}; unasPalabras[	83	] = palabra;
palabra = { PalabraIngles:"	examine	", PalabraNativa:"	Examiner  	", PalabraTraducida:"	examinar	"}; unasPalabras[	84	] = palabra;
palabra = { PalabraIngles:"	exist	", PalabraNativa:"	Exister  	", PalabraTraducida:"	existir	"}; unasPalabras[	85	] = palabra;
palabra = { PalabraIngles:"	expect	", PalabraNativa:"	Attendre  	", PalabraTraducida:"	esperar	"}; unasPalabras[	86	] = palabra;
palabra = { PalabraIngles:"	explain	", PalabraNativa:"	Expliquer  	", PalabraTraducida:"	explicar	"}; unasPalabras[	87	] = palabra;
palabra = { PalabraIngles:"	explore	", PalabraNativa:"	Explorer  	", PalabraTraducida:"	explorar	"}; unasPalabras[	88	] = palabra;
palabra = { PalabraIngles:"	express	", PalabraNativa:"	Exprimer  	", PalabraTraducida:"	expresar	"}; unasPalabras[	89	] = palabra;
palabra = { PalabraIngles:"	extend	", PalabraNativa:"	Étendre  	", PalabraTraducida:"	extender	"}; unasPalabras[	90	] = palabra;
palabra = { PalabraIngles:"	fail	", PalabraNativa:"	Échouer  	", PalabraTraducida:"	fallar	"}; unasPalabras[	91	] = palabra;
palabra = { PalabraIngles:"	fall	", PalabraNativa:"	Tomber  	", PalabraTraducida:"	caer	"}; unasPalabras[	92	] = palabra;
palabra = { PalabraIngles:"	fill	", PalabraNativa:"	Remplir  	", PalabraTraducida:"	llenar	"}; unasPalabras[	93	] = palabra;
palabra = { PalabraIngles:"	find	", PalabraNativa:"	Trouver  	", PalabraTraducida:"	encontrar	"}; unasPalabras[	94	] = palabra;
palabra = { PalabraIngles:"	finish	", PalabraNativa:"	Terminer  	", PalabraTraducida:"	finalizar	"}; unasPalabras[	95	] = palabra;
palabra = { PalabraIngles:"	fix	", PalabraNativa:"	Réparer  	", PalabraTraducida:"	arreglar	"}; unasPalabras[	96	] = palabra;
palabra = { PalabraIngles:"	fly	", PalabraNativa:"	Voler  	", PalabraTraducida:"	volar	"}; unasPalabras[	97	] = palabra;
palabra = { PalabraIngles:"	follow	", PalabraNativa:"	Suivre  	", PalabraTraducida:"	seguir	"}; unasPalabras[	98	] = palabra;
palabra = { PalabraIngles:"	force	", PalabraNativa:"	Force  	", PalabraTraducida:"	fuerza	"}; unasPalabras[	99	] = palabra;
palabra = { PalabraIngles:"	forget	", PalabraNativa:"	Oublier  	", PalabraTraducida:"	olvidar	"}; unasPalabras[	100	] = palabra;
palabra = { PalabraIngles:"	forgive	", PalabraNativa:"	Pardonner  	", PalabraTraducida:"	perdonar	"}; unasPalabras[	101	] = palabra;
palabra = { PalabraIngles:"	form	", PalabraNativa:"	Forme  	", PalabraTraducida:"	forma	"}; unasPalabras[	102	] = palabra;
palabra = { PalabraIngles:"	gain	", PalabraNativa:"	Gagner  	", PalabraTraducida:"	ganar	"}; unasPalabras[	103	] = palabra;
palabra = { PalabraIngles:"	get	", PalabraNativa:"	Obtenir  	", PalabraTraducida:"	conseguir	"}; unasPalabras[	104	] = palabra;
palabra = { PalabraIngles:"	give	", PalabraNativa:"	Donner  	", PalabraTraducida:"	dar	"}; unasPalabras[	105	] = palabra;
palabra = { PalabraIngles:"	grow	", PalabraNativa:"	Grandir  	", PalabraTraducida:"	crecer	"}; unasPalabras[	106	] = palabra;
palabra = { PalabraIngles:"	guess	", PalabraNativa:"	Deviner  	", PalabraTraducida:"	adivinar	"}; unasPalabras[	107	] = palabra;
palabra = { PalabraIngles:"	handle	", PalabraNativa:"	Gérer  	", PalabraTraducida:"	manejar	"}; unasPalabras[	108	] = palabra;
palabra = { PalabraIngles:"	happen	", PalabraNativa:"	Se passer  	", PalabraTraducida:"	suceder	"}; unasPalabras[	109	] = palabra;
palabra = { PalabraIngles:"	hate	", PalabraNativa:"	Détester  	", PalabraTraducida:"	odiar	"}; unasPalabras[	110	] = palabra;
palabra = { PalabraIngles:"	have	", PalabraNativa:"	Avoir  	", PalabraTraducida:"	tener	"}; unasPalabras[	111	] = palabra;
palabra = { PalabraIngles:"	hear	", PalabraNativa:"	Écouter  	", PalabraTraducida:"	escuchar	"}; unasPalabras[	112	] = palabra;
palabra = { PalabraIngles:"	help	", PalabraNativa:"	Aide  	", PalabraTraducida:"	ayuda	"}; unasPalabras[	113	] = palabra;
palabra = { PalabraIngles:"	hide	", PalabraNativa:"	Cacher  	", PalabraTraducida:"	esconder	"}; unasPalabras[	114	] = palabra;
palabra = { PalabraIngles:"	hit	", PalabraNativa:"	Frapper  	", PalabraTraducida:"	golpear	"}; unasPalabras[	115	] = palabra;
palabra = { PalabraIngles:"	hold	", PalabraNativa:"	Tenir  	", PalabraTraducida:"	sostener	"}; unasPalabras[	116	] = palabra;
palabra = { PalabraIngles:"	hope	", PalabraNativa:"	Espoir  	", PalabraTraducida:"	esperanza	"}; unasPalabras[	117	] = palabra;
palabra = { PalabraIngles:"	identify	", PalabraNativa:"	Identifier  	", PalabraTraducida:"	identificar	"}; unasPalabras[	118	] = palabra;
palabra = { PalabraIngles:"	imagine	", PalabraNativa:"	Imaginer  	", PalabraTraducida:"	imaginar	"}; unasPalabras[	119	] = palabra;
palabra = { PalabraIngles:"	improve	", PalabraNativa:"	Améliorer  	", PalabraTraducida:"	mejorar	"}; unasPalabras[	120	] = palabra;
palabra = { PalabraIngles:"	include	", PalabraNativa:"	Inclure  	", PalabraTraducida:"	incluir	"}; unasPalabras[	121	] = palabra;
palabra = { PalabraIngles:"	increase	", PalabraNativa:"	Augmenter  	", PalabraTraducida:"	aumentar	"}; unasPalabras[	122	] = palabra;
palabra = { PalabraIngles:"	inform	", PalabraNativa:"	Informer  	", PalabraTraducida:"	informar	"}; unasPalabras[	123	] = palabra;
palabra = { PalabraIngles:"	insist	", PalabraNativa:"	Insister  	", PalabraTraducida:"	insistir	"}; unasPalabras[	124	] = palabra;
palabra = { PalabraIngles:"	invite	", PalabraNativa:"	Inviter  	", PalabraTraducida:"	invitar	"}; unasPalabras[	125	] = palabra;
palabra = { PalabraIngles:"	involve	", PalabraNativa:"	Impliquer  	", PalabraTraducida:"	involucrar	"}; unasPalabras[	126	] = palabra;
palabra = { PalabraIngles:"	join	", PalabraNativa:"	Rejoindre  	", PalabraTraducida:"	unirse	"}; unasPalabras[	127	] = palabra;
palabra = { PalabraIngles:"	jump	", PalabraNativa:"	Sauter  	", PalabraTraducida:"	saltar	"}; unasPalabras[	128	] = palabra;
palabra = { PalabraIngles:"	keep	", PalabraNativa:"	Maintenir  	", PalabraTraducida:"	mantener	"}; unasPalabras[	129	] = palabra;
palabra = { PalabraIngles:"	kick	", PalabraNativa:"	Coup de pied  	", PalabraTraducida:"	patada	"}; unasPalabras[	130	] = palabra;
palabra = { PalabraIngles:"	kill	", PalabraNativa:"	Tuer  	", PalabraTraducida:"	matar	"}; unasPalabras[	131	] = palabra;
palabra = { PalabraIngles:"	kiss	", PalabraNativa:"	Baiser  	", PalabraTraducida:"	beso	"}; unasPalabras[	132	] = palabra;
palabra = { PalabraIngles:"	know	", PalabraNativa:"	Savoir  	", PalabraTraducida:"	saber	"}; unasPalabras[	133	] = palabra;
palabra = { PalabraIngles:"	laugh	", PalabraNativa:"	Rire  	", PalabraTraducida:"	reír	"}; unasPalabras[	134	] = palabra;
palabra = { PalabraIngles:"	lead	", PalabraNativa:"	Diriger  	", PalabraTraducida:"	dirigir	"}; unasPalabras[	135	] = palabra;
palabra = { PalabraIngles:"	learn	", PalabraNativa:"	Apprendre  	", PalabraTraducida:"	aprender	"}; unasPalabras[	136	] = palabra;
palabra = { PalabraIngles:"	leave	", PalabraNativa:"	Laisser  	", PalabraTraducida:"	dejar	"}; unasPalabras[	137	] = palabra;
palabra = { PalabraIngles:"	lend	", PalabraNativa:"	Prêter  	", PalabraTraducida:"	prestar	"}; unasPalabras[	138	] = palabra;
palabra = { PalabraIngles:"	let	", PalabraNativa:"	Quitter  	", PalabraTraducida:"	dejar	"}; unasPalabras[	139	] = palabra;
palabra = { PalabraIngles:"	like	", PalabraNativa:"	Aimer  	", PalabraTraducida:"	como	"}; unasPalabras[	140	] = palabra;
palabra = { PalabraIngles:"	listen	", PalabraNativa:"	Écouter  	", PalabraTraducida:"	escuchar	"}; unasPalabras[	141	] = palabra;
palabra = { PalabraIngles:"	live	", PalabraNativa:"	Vivre  	", PalabraTraducida:"	vivir	"}; unasPalabras[	142	] = palabra;
palabra = { PalabraIngles:"	look	", PalabraNativa:"	Regarder  	", PalabraTraducida:"	mirar	"}; unasPalabras[	143	] = palabra;
palabra = { PalabraIngles:"	lose	", PalabraNativa:"	Perdre  	", PalabraTraducida:"	perder	"}; unasPalabras[	144	] = palabra;
palabra = { PalabraIngles:"	love	", PalabraNativa:"	Aimer  	", PalabraTraducida:"	amar	"}; unasPalabras[	145	] = palabra;
palabra = { PalabraIngles:"	make	", PalabraNativa:"	Faire  	", PalabraTraducida:"	hacer	"}; unasPalabras[	146	] = palabra;
palabra = { PalabraIngles:"	manage	", PalabraNativa:"	Gérer  	", PalabraTraducida:"	administrar	"}; unasPalabras[	147	] = palabra;
palabra = { PalabraIngles:"	mark	", PalabraNativa:"	Marque  	", PalabraTraducida:"	marca	"}; unasPalabras[	148	] = palabra;
palabra = { PalabraIngles:"	marry	", PalabraNativa:"	Se marier  	", PalabraTraducida:"	casarse	"}; unasPalabras[	149	] = palabra;
palabra = { PalabraIngles:"	mean	", PalabraNativa:"	Signifier  	", PalabraTraducida:"	significar	"}; unasPalabras[	150	] = palabra;
palabra = { PalabraIngles:"	measure	", PalabraNativa:"	Mesure  	", PalabraTraducida:"	medida	"}; unasPalabras[	151	] = palabra;
palabra = { PalabraIngles:"	meet	", PalabraNativa:"	Rencontrer  	", PalabraTraducida:"	encontrarse	"}; unasPalabras[	152	] = palabra;
palabra = { PalabraIngles:"	mention	", PalabraNativa:"	Mentionner  	", PalabraTraducida:"	mencionar	"}; unasPalabras[	153	] = palabra;
palabra = { PalabraIngles:"	move	", PalabraNativa:"	Bouger  	", PalabraTraducida:"	mover	"}; unasPalabras[	154	] = palabra;
palabra = { PalabraIngles:"	need	", PalabraNativa:"	Besoin  	", PalabraTraducida:"	necesidad	"}; unasPalabras[	155	] = palabra;
palabra = { PalabraIngles:"	notice	", PalabraNativa:"	Avis  	", PalabraTraducida:"	aviso	"}; unasPalabras[	156	] = palabra;
palabra = { PalabraIngles:"	offer	", PalabraNativa:"	Offre  	", PalabraTraducida:"	oferta	"}; unasPalabras[	157	] = palabra;
palabra = { PalabraIngles:"	open	", PalabraNativa:"	Ouvert  	", PalabraTraducida:"	abierto	"}; unasPalabras[	158	] = palabra;
palabra = { PalabraIngles:"	order	", PalabraNativa:"	Ordre  	", PalabraTraducida:"	orden	"}; unasPalabras[	159	] = palabra;
palabra = { PalabraIngles:"	own	", PalabraNativa:"	Propre  	", PalabraTraducida:"	propio	"}; unasPalabras[	160	] = palabra;
palabra = { PalabraIngles:"	pay	", PalabraNativa:"	Payer  	", PalabraTraducida:"	pagar	"}; unasPalabras[	161	] = palabra;
palabra = { PalabraIngles:"	perform	", PalabraNativa:"	Réaliser  	", PalabraTraducida:"	llevar a cabo	"}; unasPalabras[	162	] = palabra;
palabra = { PalabraIngles:"	pick	", PalabraNativa:"	Choisir  	", PalabraTraducida:"	elegir	"}; unasPalabras[	163	] = palabra;
palabra = { PalabraIngles:"	plan	", PalabraNativa:"	Plan  	", PalabraTraducida:"	plan	"}; unasPalabras[	164	] = palabra;
palabra = { PalabraIngles:"	play	", PalabraNativa:"	Jouer  	", PalabraTraducida:"	jugar	"}; unasPalabras[	165	] = palabra;
palabra = { PalabraIngles:"	point	", PalabraNativa:"	Point  	", PalabraTraducida:"	punto	"}; unasPalabras[	166	] = palabra;
palabra = { PalabraIngles:"	prefer	", PalabraNativa:"	Préférer  	", PalabraTraducida:"	preferir	"}; unasPalabras[	167	] = palabra;
palabra = { PalabraIngles:"	prepare	", PalabraNativa:"	Préparer  	", PalabraTraducida:"	preparar	"}; unasPalabras[	168	] = palabra;
palabra = { PalabraIngles:"	press	", PalabraNativa:"	Appuyer  	", PalabraTraducida:"	prensa	"}; unasPalabras[	169	] = palabra;
palabra = { PalabraIngles:"	pretend	", PalabraNativa:"	Prétendre  	", PalabraTraducida:"	pretender	"}; unasPalabras[	170	] = palabra;
palabra = { PalabraIngles:"	prevent	", PalabraNativa:"	Prévenir  	", PalabraTraducida:"	prevenir	"}; unasPalabras[	171	] = palabra;
palabra = { PalabraIngles:"	promise	", PalabraNativa:"	Promettre  	", PalabraTraducida:"	promesa	"}; unasPalabras[	172	] = palabra;
palabra = { PalabraIngles:"	protect	", PalabraNativa:"	Protéger  	", PalabraTraducida:"	proteger	"}; unasPalabras[	173	] = palabra;
palabra = { PalabraIngles:"	prove	", PalabraNativa:"	Essayer  	", PalabraTraducida:"	probar	"}; unasPalabras[	174	] = palabra;
palabra = { PalabraIngles:"	pull	", PalabraNativa:"	Tirer  	", PalabraTraducida:"	jalar	"}; unasPalabras[	175	] = palabra;
palabra = { PalabraIngles:"	push	", PalabraNativa:"	Pousser  	", PalabraTraducida:"	empujar	"}; unasPalabras[	176	] = palabra;
palabra = { PalabraIngles:"	put	", PalabraNativa:"	Mettre  	", PalabraTraducida:"	poner	"}; unasPalabras[	177	] = palabra;
palabra = { PalabraIngles:"	raise	", PalabraNativa:"	Augmenter  	", PalabraTraducida:"	aumentar	"}; unasPalabras[	178	] = palabra;
palabra = { PalabraIngles:"	reach	", PalabraNativa:"	Atteindre  	", PalabraTraducida:"	alcanzar	"}; unasPalabras[	179	] = palabra;
palabra = { PalabraIngles:"	realize	", PalabraNativa:"	Se rendre compte  	", PalabraTraducida:"	darse cuenta	"}; unasPalabras[	180	] = palabra;
palabra = { PalabraIngles:"	receive	", PalabraNativa:"	Recevoir  	", PalabraTraducida:"	recibir	"}; unasPalabras[	181	] = palabra;
palabra = { PalabraIngles:"	recognize	", PalabraNativa:"	Reconnaître  	", PalabraTraducida:"	reconocer	"}; unasPalabras[	182	] = palabra;
palabra = { PalabraIngles:"	record	", PalabraNativa:"	Enregistrement  	", PalabraTraducida:"	registro	"}; unasPalabras[	183	] = palabra;
palabra = { PalabraIngles:"	reduce	", PalabraNativa:"	Réduire  	", PalabraTraducida:"	reducir	"}; unasPalabras[	184	] = palabra;
palabra = { PalabraIngles:"	reflect	", PalabraNativa:"	Refléter  	", PalabraTraducida:"	reflejar	"}; unasPalabras[	185	] = palabra;
palabra = { PalabraIngles:"	refuse	", PalabraNativa:"	Rejeter  	", PalabraTraducida:"	rechazar	"}; unasPalabras[	186	] = palabra;
palabra = { PalabraIngles:"	regret	", PalabraNativa:"	Regretter  	", PalabraTraducida:"	arrepentirse	"}; unasPalabras[	187	] = palabra;
palabra = { PalabraIngles:"	relax	", PalabraNativa:"	Se détendre  	", PalabraTraducida:"	relajarse	"}; unasPalabras[	188	] = palabra;
palabra = { PalabraIngles:"	release	", PalabraNativa:"	Libérer  	", PalabraTraducida:"	liberar	"}; unasPalabras[	189	] = palabra;
palabra = { PalabraIngles:"	remember	", PalabraNativa:"	Se souvenir  	", PalabraTraducida:"	recordar	"}; unasPalabras[	190	] = palabra;
palabra = { PalabraIngles:"	remove	", PalabraNativa:"	Supprimer  	", PalabraTraducida:"	eliminar	"}; unasPalabras[	191	] = palabra;
palabra = { PalabraIngles:"	repeat	", PalabraNativa:"	Répéter  	", PalabraTraducida:"	repetir	"}; unasPalabras[	192	] = palabra;
palabra = { PalabraIngles:"	replace	", PalabraNativa:"	Remplacer  	", PalabraTraducida:"	reemplazar	"}; unasPalabras[	193	] = palabra;
palabra = { PalabraIngles:"	reply	", PalabraNativa:"	Répondre  	", PalabraTraducida:"	responder	"}; unasPalabras[	194	] = palabra;
palabra = { PalabraIngles:"	report	", PalabraNativa:"	Rapport  	", PalabraTraducida:"	informe	"}; unasPalabras[	195	] = palabra;
palabra = { PalabraIngles:"	request	", PalabraNativa:"	Commande  	", PalabraTraducida:"	pedido	"}; unasPalabras[	196	] = palabra;
palabra = { PalabraIngles:"	rescue	", PalabraNativa:"	Sauvetage  	", PalabraTraducida:"	rescate	"}; unasPalabras[	197	] = palabra;
palabra = { PalabraIngles:"	return	", PalabraNativa:"	Rendre  	", PalabraTraducida:"	devolver	"}; unasPalabras[	198	] = palabra;
palabra = { PalabraIngles:"	reveal	", PalabraNativa:"	Révéler  	", PalabraTraducida:"	revelar	"}; unasPalabras[	199	] = palabra;
palabra = { PalabraIngles:"	risk	", PalabraNativa:"	Risque  	", PalabraTraducida:"	riesgo	"}; unasPalabras[	200	] = palabra;
palabra = { PalabraIngles:"	run	", PalabraNativa:"	Courir  	", PalabraTraducida:"	correr	"}; unasPalabras[	201	] = palabra;
palabra = { PalabraIngles:"	save	", PalabraNativa:"	Économiser  	", PalabraTraducida:"	ahorrar	"}; unasPalabras[	202	] = palabra;
palabra = { PalabraIngles:"	say	", PalabraNativa:"	Dire  	", PalabraTraducida:"	decir	"}; unasPalabras[	203	] = palabra;
palabra = { PalabraIngles:"	see	", PalabraNativa:"	Voir  	", PalabraTraducida:"	ver	"}; unasPalabras[	204	] = palabra;
palabra = { PalabraIngles:"	seem	", PalabraNativa:"	Sembler  	", PalabraTraducida:"	parecer	"}; unasPalabras[	205	] = palabra;
palabra = { PalabraIngles:"	sell	", PalabraNativa:"	Vendre  	", PalabraTraducida:"	vender	"}; unasPalabras[	206	] = palabra;
palabra = { PalabraIngles:"	send	", PalabraNativa:"	Envoyer  	", PalabraTraducida:"	enviar	"}; unasPalabras[	207	] = palabra;
palabra = { PalabraIngles:"	serve	", PalabraNativa:"	Servir  	", PalabraTraducida:"	atender	"}; unasPalabras[	208	] = palabra;
palabra = { PalabraIngles:"	set	", PalabraNativa:"	Placer  	", PalabraTraducida:"	colocar	"}; unasPalabras[	209	] = palabra;
palabra = { PalabraIngles:"	share	", PalabraNativa:"	Partager  	", PalabraTraducida:"	compartir	"}; unasPalabras[	210	] = palabra;
palabra = { PalabraIngles:"	show	", PalabraNativa:"	Spectacle  	", PalabraTraducida:"	espectáculo	"}; unasPalabras[	211	] = palabra;
palabra = { PalabraIngles:"	shut	", PalabraNativa:"	Fermer  	", PalabraTraducida:"	cerrar	"}; unasPalabras[	212	] = palabra;
palabra = { PalabraIngles:"	sing	", PalabraNativa:"	Chanter  	", PalabraTraducida:"	cantar	"}; unasPalabras[	213	] = palabra;
palabra = { PalabraIngles:"	sit	", PalabraNativa:"	S'asseoir  	", PalabraTraducida:"	sentarse	"}; unasPalabras[	214	] = palabra;
palabra = { PalabraIngles:"	sleep	", PalabraNativa:"	Dormir  	", PalabraTraducida:"	dormir	"}; unasPalabras[	215	] = palabra;
palabra = { PalabraIngles:"	smile	", PalabraNativa:"	Sourire  	", PalabraTraducida:"	sonrisa	"}; unasPalabras[	216	] = palabra;
palabra = { PalabraIngles:"	solve	", PalabraNativa:"	Résoudre  	", PalabraTraducida:"	resolver	"}; unasPalabras[	217	] = palabra;
palabra = { PalabraIngles:"	sound	", PalabraNativa:"	Son  	", PalabraTraducida:"	sonido	"}; unasPalabras[	218	] = palabra;
palabra = { PalabraIngles:"	speak	", PalabraNativa:"	Parler  	", PalabraTraducida:"	hablar	"}; unasPalabras[	219	] = palabra;
palabra = { PalabraIngles:"	spend	", PalabraNativa:"	Dépenser  	", PalabraTraducida:"	gastar	"}; unasPalabras[	220	] = palabra;
palabra = { PalabraIngles:"	stand	", PalabraNativa:"	Se lever  	", PalabraTraducida:"	pararse	"}; unasPalabras[	221	] = palabra;
palabra = { PalabraIngles:"	start	", PalabraNativa:"	Commencer  	", PalabraTraducida:"	comenzar	"}; unasPalabras[	222	] = palabra;
palabra = { PalabraIngles:"	stay	", PalabraNativa:"	Rester  	", PalabraTraducida:"	permanecer	"}; unasPalabras[	223	] = palabra;
palabra = { PalabraIngles:"	steal	", PalabraNativa:"	Voler  	", PalabraTraducida:"	robar	"}; unasPalabras[	224	] = palabra;
palabra = { PalabraIngles:"	stop	", PalabraNativa:"	Arrêter  	", PalabraTraducida:"	detener	"}; unasPalabras[	225	] = palabra;
palabra = { PalabraIngles:"	study	", PalabraNativa:"	Étudier  	", PalabraTraducida:"	estudiar	"}; unasPalabras[	226	] = palabra;
palabra = { PalabraIngles:"	succeed	", PalabraNativa:"	Réussir  	", PalabraTraducida:"	tener éxito	"}; unasPalabras[	227	] = palabra;
palabra = { PalabraIngles:"	suffer	", PalabraNativa:"	Souffrir  	", PalabraTraducida:"	sufrir	"}; unasPalabras[	228	] = palabra;
palabra = { PalabraIngles:"	suggest	", PalabraNativa:"	Suggérer  	", PalabraTraducida:"	sugerir	"}; unasPalabras[	229	] = palabra;
palabra = { PalabraIngles:"	supply	", PalabraNativa:"	Fournir  	", PalabraTraducida:"	suministrar	"}; unasPalabras[	230	] = palabra;
palabra = { PalabraIngles:"	support	", PalabraNativa:"	Soutien  	", PalabraTraducida:"	apoyo	"}; unasPalabras[	231	] = palabra;
palabra = { PalabraIngles:"	suppose	", PalabraNativa:"	Supposer  	", PalabraTraducida:"	suponer	"}; unasPalabras[	232	] = palabra;
palabra = { PalabraIngles:"	surprise	", PalabraNativa:"	Surprise  	", PalabraTraducida:"	sorpresa	"}; unasPalabras[	233	] = palabra;
palabra = { PalabraIngles:"	take	", PalabraNativa:"	Porter  	", PalabraTraducida:"	llevar	"}; unasPalabras[	234	] = palabra;
palabra = { PalabraIngles:"	talk	", PalabraNativa:"	Parler  	", PalabraTraducida:"	hablar	"}; unasPalabras[	235	] = palabra;
palabra = { PalabraIngles:"	teach	", PalabraNativa:"	Enseigner  	", PalabraTraducida:"	enseñar	"}; unasPalabras[	236	] = palabra;
palabra = { PalabraIngles:"	tell	", PalabraNativa:"	Dire  	", PalabraTraducida:"	decir	"}; unasPalabras[	237	] = palabra;
palabra = { PalabraIngles:"	test	", PalabraNativa:"	Test  	", PalabraTraducida:"	prueba	"}; unasPalabras[	238	] = palabra;
palabra = { PalabraIngles:"	thank	", PalabraNativa:"	Remercier  	", PalabraTraducida:"	agradecer	"}; unasPalabras[	239	] = palabra;
palabra = { PalabraIngles:"	think	", PalabraNativa:"	Penser  	", PalabraTraducida:"	pensar	"}; unasPalabras[	240	] = palabra;
palabra = { PalabraIngles:"	throw	", PalabraNativa:"	Jeter  	", PalabraTraducida:"	tirar	"}; unasPalabras[	241	] = palabra;
palabra = { PalabraIngles:"	touch	", PalabraNativa:"	Toucher  	", PalabraTraducida:"	tocar	"}; unasPalabras[	242	] = palabra;
palabra = { PalabraIngles:"	train	", PalabraNativa:"	Train  	", PalabraTraducida:"	tren	"}; unasPalabras[	243	] = palabra;
palabra = { PalabraIngles:"	travel	", PalabraNativa:"	Voyager  	", PalabraTraducida:"	viajar	"}; unasPalabras[	244	] = palabra;
palabra = { PalabraIngles:"	treat	", PalabraNativa:"	Traiter  	", PalabraTraducida:"	tratar	"}; unasPalabras[	245	] = palabra;
palabra = { PalabraIngles:"	try	", PalabraNativa:"	Essayer  	", PalabraTraducida:"	intentar	"}; unasPalabras[	246	] = palabra;
palabra = { PalabraIngles:"	turn	", PalabraNativa:"	Plier  	", PalabraTraducida:"	doblar	"}; unasPalabras[	247	] = palabra;
palabra = { PalabraIngles:"	understand	", PalabraNativa:"	Comprendre  	", PalabraTraducida:"	entender	"}; unasPalabras[	248	] = palabra;
palabra = { PalabraIngles:"	use	", PalabraNativa:"	Utiliser  	", PalabraTraducida:"	usar	"}; unasPalabras[	249	] = palabra;
palabra = { PalabraIngles:"	visit	", PalabraNativa:"	Visiter  	", PalabraTraducida:"	visita	"}; unasPalabras[	250	] = palabra;
palabra = { PalabraIngles:"	wait	", PalabraNativa:"	Espérer  	", PalabraTraducida:"	esperar	"}; unasPalabras[	251	] = palabra;
palabra = { PalabraIngles:"	walk	", PalabraNativa:"	Marcher  	", PalabraTraducida:"	caminar	"}; unasPalabras[	252	] = palabra;
palabra = { PalabraIngles:"	want	", PalabraNativa:"	Souhaiter  	", PalabraTraducida:"	desear	"}; unasPalabras[	253	] = palabra;
palabra = { PalabraIngles:"	warn	", PalabraNativa:"	Avertir  	", PalabraTraducida:"	advertir	"}; unasPalabras[	254	] = palabra;
palabra = { PalabraIngles:"	wash	", PalabraNativa:"	Laver  	", PalabraTraducida:"	lavar	"}; unasPalabras[	255	] = palabra;
palabra = { PalabraIngles:"	watch	", PalabraNativa:"	Regarder  	", PalabraTraducida:"	mirar	"}; unasPalabras[	256	] = palabra;
palabra = { PalabraIngles:"	wear	", PalabraNativa:"	Porter  	", PalabraTraducida:"	tener puesto	"}; unasPalabras[	257	] = palabra;
palabra = { PalabraIngles:"	win	", PalabraNativa:"	Gagner  	", PalabraTraducida:"	ganar	"}; unasPalabras[	258	] = palabra;
palabra = { PalabraIngles:"	wish	", PalabraNativa:"	Souhaiter  	", PalabraTraducida:"	desear	"}; unasPalabras[	259	] = palabra;
palabra = { PalabraIngles:"	wonder	", PalabraNativa:"	Se demander  	", PalabraTraducida:"	preguntarse	"}; unasPalabras[	260	] = palabra;
palabra = { PalabraIngles:"	work	", PalabraNativa:"	Travailler  	", PalabraTraducida:"	trabajar	"}; unasPalabras[	261	] = palabra;
palabra = { PalabraIngles:"	worry	", PalabraNativa:"	S'inquiéter  	", PalabraTraducida:"	preocuparse	"}; unasPalabras[	262	] = palabra;
palabra = { PalabraIngles:"	write	", PalabraNativa:"	Écrire  	", PalabraTraducida:"	escribir	"}; unasPalabras[	263	] = palabra;

			
	cantidadPalabras = unasPalabras.length;
}