
	
$(function () {
	Load();
});	

function Load()
{
	SeteoVariablesGlobales();
	document.getElementById("rbtn1").checked = 1;
	PracticarUnoNuevo();
}	

function SeteoVariablesGlobales()
{
	//document.getElementById("lblResultado").style.visibility = "hidden";
	//$("#lblEstado").text("0/1");	
palabra = { PalabraIngles:"	add 1	", PalabraNativa:"	Ajouter  	", PalabraTraducida:"	Agregar  	"}; unasPalabras[	0	] = palabra;
palabra = { PalabraIngles:"	ask	", PalabraNativa:"	Demander  	", PalabraTraducida:"	Pedir  	"}; unasPalabras[	1	] = palabra;
palabra = { PalabraIngles:"	bake	", PalabraNativa:"	Cuire  	", PalabraTraducida:"	Cocinar  	"}; unasPalabras[	2	] = palabra;
palabra = { PalabraIngles:"	barbecue	", PalabraNativa:"	Barbecue  	", PalabraTraducida:"	Parrilla  	"}; unasPalabras[	3	] = palabra;
palabra = { PalabraIngles:"	bathing	", PalabraNativa:"	Baignade  	", PalabraTraducida:"	Baño  	"}; unasPalabras[	4	] = palabra;
palabra = { PalabraIngles:"	bend 1	", PalabraNativa:"	Courbure  	", PalabraTraducida:"	Curvatura  	"}; unasPalabras[	5	] = palabra;
palabra = { PalabraIngles:"	bend	", PalabraNativa:"	Pliez  	", PalabraTraducida:"	Doblar  	"}; unasPalabras[	6	] = palabra;
palabra = { PalabraIngles:"	boil 1	", PalabraNativa:"	Faire bouillir  	", PalabraTraducida:"	Hervir  	"}; unasPalabras[	7	] = palabra;
palabra = { PalabraIngles:"	bounce	", PalabraNativa:"	Rebondir  	", PalabraTraducida:"	Rebotar  	"}; unasPalabras[	8	] = palabra;
palabra = { PalabraIngles:"	bow 1	", PalabraNativa:"	Arc  	", PalabraTraducida:"	Arco  	"}; unasPalabras[	9	] = palabra;
palabra = { PalabraIngles:"	break	", PalabraNativa:"	Pause  	", PalabraTraducida:"	Pausa  	"}; unasPalabras[	10	] = palabra;
palabra = { PalabraIngles:"	brush your hair	", PalabraNativa:"	Brosse tes cheveux  	", PalabraTraducida:"	Cepillarse el cabello  	"}; unasPalabras[	11	] = palabra;
palabra = { PalabraIngles:"	brush your teeth	", PalabraNativa:"	Brosse-toi les dents  	", PalabraTraducida:"	Cepillarse los dientes  	"}; unasPalabras[	12	] = palabra;
palabra = { PalabraIngles:"	buy	", PalabraNativa:"	Acheter  	", PalabraTraducida:"	Comprar  	"}; unasPalabras[	13	] = palabra;
palabra = { PalabraIngles:"	calculate 1	", PalabraNativa:"	Calculer  	", PalabraTraducida:"	Calcular  	"}; unasPalabras[	14	] = palabra;
palabra = { PalabraIngles:"	camping 1	", PalabraNativa:"	Camping  	", PalabraTraducida:"	Acampar  	"}; unasPalabras[	15	] = palabra;
palabra = { PalabraIngles:"	carry	", PalabraNativa:"	Porter  	", PalabraTraducida:"	Llevar  	"}; unasPalabras[	16	] = palabra;
palabra = { PalabraIngles:"	Cartwheel	", PalabraNativa:"	Roue de charrette  	", PalabraTraducida:"	Rueda de carreta  	"}; unasPalabras[	17	] = palabra;
palabra = { PalabraIngles:"	catch 3	", PalabraNativa:"	Attraper  	", PalabraTraducida:"	Atrapar  	"}; unasPalabras[	18	] = palabra;
palabra = { PalabraIngles:"	catch	", PalabraNativa:"	Capture  	", PalabraTraducida:"	Capturar  	"}; unasPalabras[	19	] = palabra;
palabra = { PalabraIngles:"	change the sheets	", PalabraNativa:"	Changer les draps  	", PalabraTraducida:"	Cambiar las sábanas  	"}; unasPalabras[	20	] = palabra;
palabra = { PalabraIngles:"	chop 1	", PalabraNativa:"	Hacher  	", PalabraTraducida:"	Picar  	"}; unasPalabras[	21	] = palabra;
palabra = { PalabraIngles:"	clap	", PalabraNativa:"	Taper  	", PalabraTraducida:"	Golpear  	"}; unasPalabras[	22	] = palabra;
palabra = { PalabraIngles:"	clean the windows	", PalabraNativa:"	Nettoyer les fenêtres  	", PalabraTraducida:"	Limpiar las ventanas  	"}; unasPalabras[	23	] = palabra;
palabra = { PalabraIngles:"	cleaning	", PalabraNativa:"	Nettoyage  	", PalabraTraducida:"	Limpieza  	"}; unasPalabras[	24	] = palabra;
palabra = { PalabraIngles:"	climb	", PalabraNativa:"	Montée  	", PalabraTraducida:"	Subida  	"}; unasPalabras[	25	] = palabra;
palabra = { PalabraIngles:"	close 1	", PalabraNativa:"	Fermer  	", PalabraTraducida:"	Cerrar  	"}; unasPalabras[	26	] = palabra;
palabra = { PalabraIngles:"	close	", PalabraNativa:"	Fermer  	", PalabraTraducida:"	Cerrar  	"}; unasPalabras[	27	] = palabra;
palabra = { PalabraIngles:"	cook 1	", PalabraNativa:"	Cuisinier  	", PalabraTraducida:"	Cocinero  	"}; unasPalabras[	28	] = palabra;
palabra = { PalabraIngles:"	cook	", PalabraNativa:"	Cuisinier  	", PalabraTraducida:"	Cocinero  	"}; unasPalabras[	29	] = palabra;
palabra = { PalabraIngles:"	count	", PalabraNativa:"	Compter  	", PalabraTraducida:"	Contar  	"}; unasPalabras[	30	] = palabra;
palabra = { PalabraIngles:"	counting	", PalabraNativa:"	Compte  	", PalabraTraducida:"	Cuenta  	"}; unasPalabras[	31	] = palabra;
palabra = { PalabraIngles:"	crawl	", PalabraNativa:"	Crawl  	", PalabraTraducida:"	Nadar estilo libre  	"}; unasPalabras[	32	] = palabra;
palabra = { PalabraIngles:"	cry 1	", PalabraNativa:"	Pleurer  	", PalabraTraducida:"	Llorar  	"}; unasPalabras[	33	] = palabra;
palabra = { PalabraIngles:"	cry 2	", PalabraNativa:"	Pleurer  	", PalabraTraducida:"	Llorar  	"}; unasPalabras[	34	] = palabra;
palabra = { PalabraIngles:"	cut 1	", PalabraNativa:"	Couper  	", PalabraTraducida:"	Cortar  	"}; unasPalabras[	35	] = palabra;
palabra = { PalabraIngles:"	cut the grass	", PalabraNativa:"	Couper l'herbe  	", PalabraTraducida:"	Cortar el césped  	"}; unasPalabras[	36	] = palabra;
palabra = { PalabraIngles:"	cut	", PalabraNativa:"	Couper  	", PalabraTraducida:"	Cortar  	"}; unasPalabras[	37	] = palabra;
palabra = { PalabraIngles:"	cycling	", PalabraNativa:"	Cyclisme  	", PalabraTraducida:"	Andar en bicicleta  	"}; unasPalabras[	38	] = palabra;
palabra = { PalabraIngles:"	dance 2	", PalabraNativa:"	Danse  	", PalabraTraducida:"	Bailar  	"}; unasPalabras[	39	] = palabra;
palabra = { PalabraIngles:"	dance	", PalabraNativa:"	Danse  	", PalabraTraducida:"	Bailar  	"}; unasPalabras[	40	] = palabra;
palabra = { PalabraIngles:"	Desayunar	", PalabraNativa:"	Desayunar  	", PalabraTraducida:"	Desayunar  	"}; unasPalabras[	41	] = palabra;
palabra = { PalabraIngles:"	dig	", PalabraNativa:"	Creuser  	", PalabraTraducida:"	Excavar  	"}; unasPalabras[	42	] = palabra;
palabra = { PalabraIngles:"	Dine	", PalabraNativa:"	Dîner  	", PalabraTraducida:"	Cenar  	"}; unasPalabras[	43	] = palabra;
palabra = { PalabraIngles:"	dive	", PalabraNativa:"	Se plonger  	", PalabraTraducida:"	Sumergirse  	"}; unasPalabras[	44	] = palabra;
palabra = { PalabraIngles:"	do the dishes	", PalabraNativa:"	Faire la vaisselle  	", PalabraTraducida:"	Lavar los platos  	"}; unasPalabras[	45	] = palabra;
palabra = { PalabraIngles:"	drag	", PalabraNativa:"	Traîne  	", PalabraTraducida:"	Arrastrarse  	"}; unasPalabras[	46	] = palabra;
palabra = { PalabraIngles:"	draw	", PalabraNativa:"	Dessiner  	", PalabraTraducida:"	Dibujar  	"}; unasPalabras[	47	] = palabra;
palabra = { PalabraIngles:"	dream	", PalabraNativa:"	Rêver  	", PalabraTraducida:"	Soñar  	"}; unasPalabras[	48	] = palabra;
palabra = { PalabraIngles:"	dribble	", PalabraNativa:"	Dribble  	", PalabraTraducida:"	Driblar  	"}; unasPalabras[	49	] = palabra;
palabra = { PalabraIngles:"	Drill 1	", PalabraNativa:"	Exercice  	", PalabraTraducida:"	Ejercicio  	"}; unasPalabras[	50	] = palabra;
palabra = { PalabraIngles:"	drink 1	", PalabraNativa:"	Boire  	", PalabraTraducida:"	Beber  	"}; unasPalabras[	51	] = palabra;
palabra = { PalabraIngles:"	drink	", PalabraNativa:"	Boisson  	", PalabraTraducida:"	Bebida  	"}; unasPalabras[	52	] = palabra;
palabra = { PalabraIngles:"	drive a nail	", PalabraNativa:"	Enfoncer un clou  	", PalabraTraducida:"	Clavar un clavo  	"}; unasPalabras[	53	] = palabra;
palabra = { PalabraIngles:"	drive to work	", PalabraNativa:"	Se rendre au travail  	", PalabraTraducida:"	Ir al trabajo  	"}; unasPalabras[	54	] = palabra;
palabra = { PalabraIngles:"	Drop	", PalabraNativa:"	Laissez tomber  	", PalabraTraducida:"	Dejar caer  	"}; unasPalabras[	55	] = palabra;
palabra = { PalabraIngles:"	dry	", PalabraNativa:"	Sec  	", PalabraTraducida:"	Secar  	"}; unasPalabras[	56	] = palabra;
palabra = { PalabraIngles:"	eat 1	", PalabraNativa:"	Manger  	", PalabraTraducida:"	Comer  	"}; unasPalabras[	57	] = palabra;
palabra = { PalabraIngles:"	eat	", PalabraNativa:"	Manger  	", PalabraTraducida:"	Comer  	"}; unasPalabras[	58	] = palabra;
palabra = { PalabraIngles:"	exercise	", PalabraNativa:"	exercise	", PalabraTraducida:"	Ejercicio  	"}; unasPalabras[	59	] = palabra;
palabra = { PalabraIngles:"	experiment 1	", PalabraNativa:"	Expérience  	", PalabraTraducida:"	Experiencia  	"}; unasPalabras[	60	] = palabra;
palabra = { PalabraIngles:"	explain	", PalabraNativa:"	Explique  	", PalabraTraducida:"	Explicar  	"}; unasPalabras[	61	] = palabra;
palabra = { PalabraIngles:"	fall	", PalabraNativa:"	Tomber  	", PalabraTraducida:"	Caer  	"}; unasPalabras[	62	] = palabra;
palabra = { PalabraIngles:"	feed the dog	", PalabraNativa:"	Nourrir le chien  	", PalabraTraducida:"	Alimentar al perro  	"}; unasPalabras[	63	] = palabra;
palabra = { PalabraIngles:"	fight 1	", PalabraNativa:"	Se battre  	", PalabraTraducida:"	Pelear  	"}; unasPalabras[	64	] = palabra;
palabra = { PalabraIngles:"	fishing 1	", PalabraNativa:"	Pêche  	", PalabraTraducida:"	Pescar  	"}; unasPalabras[	65	] = palabra;
palabra = { PalabraIngles:"	fly 1	", PalabraNativa:"	Voler  	", PalabraTraducida:"	Volar  	"}; unasPalabras[	66	] = palabra;
palabra = { PalabraIngles:"	flying a kite	", PalabraNativa:"	Faire voler un cerf-volant  	", PalabraTraducida:"	Volar una cometa  	"}; unasPalabras[	67	] = palabra;
palabra = { PalabraIngles:"	fold the laundry	", PalabraNativa:"	Plier le linge  	", PalabraTraducida:"	Doblar la ropa  	"}; unasPalabras[	68	] = palabra;
palabra = { PalabraIngles:"	FOLD THE SCARF	", PalabraNativa:"	Plier l'écharpe  	", PalabraTraducida:"	Doblar la bufanda  	"}; unasPalabras[	69	] = palabra;
palabra = { PalabraIngles:"	fry	", PalabraNativa:"	Frire  	", PalabraTraducida:"	Freír  	"}; unasPalabras[	70	] = palabra;
palabra = { PalabraIngles:"	get dressed	", PalabraNativa:"	S'habiller  	", PalabraTraducida:"	Vestirse  	"}; unasPalabras[	71	] = palabra;
palabra = { PalabraIngles:"	get home	", PalabraNativa:"	Rentrer à la maison  	", PalabraTraducida:"	Volver a casa  	"}; unasPalabras[	72	] = palabra;
palabra = { PalabraIngles:"	give 1	", PalabraNativa:"	Donne  	", PalabraTraducida:"	Dar  	"}; unasPalabras[	73	] = palabra;
palabra = { PalabraIngles:"	give	", PalabraNativa:"	Donner  	", PalabraTraducida:"	Dar  	"}; unasPalabras[	74	] = palabra;
palabra = { PalabraIngles:"	go for a walk 1	", PalabraNativa:"	Faire une promenade  	", PalabraTraducida:"	Dar un paseo  	"}; unasPalabras[	75	] = palabra;
palabra = { PalabraIngles:"	go out with friend	", PalabraNativa:"	Sortir avec un ami  	", PalabraTraducida:"	Salir con un amigo  	"}; unasPalabras[	76	] = palabra;
palabra = { PalabraIngles:"	go shopping	", PalabraNativa:"	Aller faire les courses  	", PalabraTraducida:"	Ir de compras  	"}; unasPalabras[	77	] = palabra;
palabra = { PalabraIngles:"	go to bed	", PalabraNativa:"	Aller au lit  	", PalabraTraducida:"	Ir a la cama  	"}; unasPalabras[	78	] = palabra;
palabra = { PalabraIngles:"	go to school.	", PalabraNativa:"	Va à l'école  	", PalabraTraducida:"	Ir a la escuela  	"}; unasPalabras[	79	] = palabra;
palabra = { PalabraIngles:"	grate	", PalabraNativa:"	Grille  	", PalabraTraducida:"	Parrilla  	"}; unasPalabras[	80	] = palabra;
palabra = { PalabraIngles:"	Hang the clothes	", PalabraNativa:"	Accrocher les vêtements  	", PalabraTraducida:"	Colgar la ropa  	"}; unasPalabras[	81	] = palabra;
palabra = { PalabraIngles:"	hang the picture	", PalabraNativa:"	Accrocher la photo  	", PalabraTraducida:"	Colgar la foto  	"}; unasPalabras[	82	] = palabra;
palabra = { PalabraIngles:"	have a break	", PalabraNativa:"	Prends une pause  	", PalabraTraducida:"	Tomar un descanso  	"}; unasPalabras[	83	] = palabra;
palabra = { PalabraIngles:"	hit 1	", PalabraNativa:"	Frapper  	", PalabraTraducida:"	Golpear  	"}; unasPalabras[	84	] = palabra;
palabra = { PalabraIngles:"	hit 3	", PalabraNativa:"	Frapper  	", PalabraTraducida:"	Golpear  	"}; unasPalabras[	85	] = palabra;
palabra = { PalabraIngles:"	hold	", PalabraNativa:"	Tenir  	", PalabraTraducida:"	Sostener  	"}; unasPalabras[	86	] = palabra;
palabra = { PalabraIngles:"	hop	", PalabraNativa:"	Saut  	", PalabraTraducida:"	Salto  	"}; unasPalabras[	87	] = palabra;
palabra = { PalabraIngles:"	hug	", PalabraNativa:"	Étreinte  	", PalabraTraducida:"	Abrazo  	"}; unasPalabras[	88	] = palabra;
palabra = { PalabraIngles:"	iron the clothes.	", PalabraNativa:"	Repasser les vêtements  	", PalabraTraducida:"	Planchar la ropa  	"}; unasPalabras[	89	] = palabra;
palabra = { PalabraIngles:"	iron the clothes	", PalabraNativa:"	Repasser les vêtements  	", PalabraTraducida:"	Planchar la ropa  	"}; unasPalabras[	90	] = palabra;
palabra = { PalabraIngles:"	jump 1	", PalabraNativa:"	Saut  	", PalabraTraducida:"	Salto  	"}; unasPalabras[	91	] = palabra;
palabra = { PalabraIngles:"	jump 2	", PalabraNativa:"	Saut  	", PalabraTraducida:"	Salto  	"}; unasPalabras[	92	] = palabra;
palabra = { PalabraIngles:"	jump	", PalabraNativa:"	Saut  	", PalabraTraducida:"	Salto  	"}; unasPalabras[	93	] = palabra;
palabra = { PalabraIngles:"	Kick	", PalabraNativa:"	Donner un coup  	", PalabraTraducida:"	Dar un golpe  	"}; unasPalabras[	94	] = palabra;
palabra = { PalabraIngles:"	kiss 1	", PalabraNativa:"	Bisou  	", PalabraTraducida:"	Beso  	"}; unasPalabras[	95	] = palabra;
palabra = { PalabraIngles:"	kiss	", PalabraNativa:"	Baiser  	", PalabraTraducida:"	Besar  	"}; unasPalabras[	96	] = palabra;
palabra = { PalabraIngles:"	kneel 1	", PalabraNativa:"	Agenouiller  	", PalabraTraducida:"	Arrodillarse  	"}; unasPalabras[	97	] = palabra;
palabra = { PalabraIngles:"	kneel	", PalabraNativa:"	S'agenouiller  	", PalabraTraducida:"	Arrodillarse  	"}; unasPalabras[	98	] = palabra;
palabra = { PalabraIngles:"	knit	", PalabraNativa:"	Tricoter  	", PalabraTraducida:"	Tejer  	"}; unasPalabras[	99	] = palabra;
palabra = { PalabraIngles:"	laugh	", PalabraNativa:"	Rire  	", PalabraTraducida:"	Reír  	"}; unasPalabras[	100	] = palabra;
palabra = { PalabraIngles:"	Laundry	", PalabraNativa:"	Blanchisserie  	", PalabraTraducida:"	Lavandería  	"}; unasPalabras[	101	] = palabra;
palabra = { PalabraIngles:"	layer	", PalabraNativa:"	Couche  	", PalabraTraducida:"	Pañal  	"}; unasPalabras[	102	] = palabra;
palabra = { PalabraIngles:"	lean	", PalabraNativa:"	Maigre  	", PalabraTraducida:"	Delgado  	"}; unasPalabras[	103	] = palabra;
palabra = { PalabraIngles:"	leap 1	", PalabraNativa:"	Saut  	", PalabraTraducida:"	Salto  	"}; unasPalabras[	104	] = palabra;
palabra = { PalabraIngles:"	lie down	", PalabraNativa:"	S'allonger  	", PalabraTraducida:"	Acostarse  	"}; unasPalabras[	105	] = palabra;
palabra = { PalabraIngles:"	lift 1	", PalabraNativa:"	Ascenseur  	", PalabraTraducida:"	Ascensor  	"}; unasPalabras[	106	] = palabra;
palabra = { PalabraIngles:"	lift 3	", PalabraNativa:"	Ascenseur  	", PalabraTraducida:"	Ascensor  	"}; unasPalabras[	107	] = palabra;
palabra = { PalabraIngles:"	light	", PalabraNativa:"	Lumière  	", PalabraTraducida:"	Luz  	"}; unasPalabras[	108	] = palabra;
palabra = { PalabraIngles:"	listen	", PalabraNativa:"	Écoute  	", PalabraTraducida:"	Escuchar  	"}; unasPalabras[	109	] = palabra;
palabra = { PalabraIngles:"	Look	", PalabraNativa:"	Regardez  	", PalabraTraducida:"	Mirar  	"}; unasPalabras[	110	] = palabra;
palabra = { PalabraIngles:"	Make dinner	", PalabraNativa:"	Faire le dîner  	", PalabraTraducida:"	Preparar la cena  	"}; unasPalabras[	111	] = palabra;
palabra = { PalabraIngles:"	make my bed	", PalabraNativa:"	Faire mon lit  	", PalabraTraducida:"	Tender mi cama  	"}; unasPalabras[	112	] = palabra;
palabra = { PalabraIngles:"	make the bed	", PalabraNativa:"	Faire le lit  	", PalabraTraducida:"	Tender la cama  	"}; unasPalabras[	113	] = palabra;
palabra = { PalabraIngles:"	march	", PalabraNativa:"	Mars  	", PalabraTraducida:"	Marzo  	"}; unasPalabras[	114	] = palabra;
palabra = { PalabraIngles:"	melt	", PalabraNativa:"	Fondre  	", PalabraTraducida:"	Derretir  	"}; unasPalabras[	115	] = palabra;
palabra = { PalabraIngles:"	mix	", PalabraNativa:"	Mélanger  	", PalabraTraducida:"	Mezclar  	"}; unasPalabras[	116	] = palabra;
palabra = { PalabraIngles:"	nobg	", PalabraNativa:"	Nobg  	", PalabraTraducida:"	Nobg  	"}; unasPalabras[	117	] = palabra;
palabra = { PalabraIngles:"	observe	", PalabraNativa:"	Observer  	", PalabraTraducida:"	Observar  	"}; unasPalabras[	118	] = palabra;
palabra = { PalabraIngles:"	open 1	", PalabraNativa:"	Ouvert  	", PalabraTraducida:"	Abierto  	"}; unasPalabras[	119	] = palabra;
palabra = { PalabraIngles:"	Open	", PalabraNativa:"	Ouvrir  	", PalabraTraducida:"	Abrir  	"}; unasPalabras[	120	] = palabra;
palabra = { PalabraIngles:"	order	", PalabraNativa:"	Ordre  	", PalabraTraducida:"	Ordenar  	"}; unasPalabras[	121	] = palabra;
palabra = { PalabraIngles:"	paint 1	", PalabraNativa:"	Peinture  	", PalabraTraducida:"	Pintura  	"}; unasPalabras[	122	] = palabra;
palabra = { PalabraIngles:"	paint the house	", PalabraNativa:"	Peindre la maison  	", PalabraTraducida:"	Pintar la casa  	"}; unasPalabras[	123	] = palabra;
palabra = { PalabraIngles:"	paint the picture	", PalabraNativa:"	Peindre le tableau  	", PalabraTraducida:"	Pintar el cuadro  	"}; unasPalabras[	124	] = palabra;
palabra = { PalabraIngles:"	paint	", PalabraNativa:"	Peindre  	", PalabraTraducida:"	Pintar  	"}; unasPalabras[	125	] = palabra;
palabra = { PalabraIngles:"	pass	", PalabraNativa:"	Passer  	", PalabraTraducida:"	Pasar  	"}; unasPalabras[	126	] = palabra;
palabra = { PalabraIngles:"	pay	", PalabraNativa:"	Payer  	", PalabraTraducida:"	Pagar  	"}; unasPalabras[	127	] = palabra;
palabra = { PalabraIngles:"	peel	", PalabraNativa:"	Peler  	", PalabraTraducida:"	Pelar  	"}; unasPalabras[	128	] = palabra;
palabra = { PalabraIngles:"	pick up	", PalabraNativa:"	Ramasser  	", PalabraTraducida:"	Recoger  	"}; unasPalabras[	129	] = palabra;
palabra = { PalabraIngles:"	pinch	", PalabraNativa:"	Pincer  	", PalabraTraducida:"	Pellizcar  	"}; unasPalabras[	130	] = palabra;
palabra = { PalabraIngles:"	play 1	", PalabraNativa:"	Jouer  	", PalabraTraducida:"	Jugar  	"}; unasPalabras[	131	] = palabra;
palabra = { PalabraIngles:"	play the guitar	", PalabraNativa:"	Jouer de la guitare  	", PalabraTraducida:"	Tocar la guitarra  	"}; unasPalabras[	132	] = palabra;
palabra = { PalabraIngles:"	Play with friends	", PalabraNativa:"	Jouer avec des amis  	", PalabraTraducida:"	Jugar con amigos  	"}; unasPalabras[	133	] = palabra;
palabra = { PalabraIngles:"	play	", PalabraNativa:"	Jouer  	", PalabraTraducida:"	Jugar  	"}; unasPalabras[	134	] = palabra;
palabra = { PalabraIngles:"	playing an instrument 2	", PalabraNativa:"	Jouer d'un instrument  	", PalabraTraducida:"	Tocar un instrumento  	"}; unasPalabras[	135	] = palabra;
palabra = { PalabraIngles:"	playing cards	", PalabraNativa:"	Jouer aux cartes  	", PalabraTraducida:"	Jugar a las cartas  	"}; unasPalabras[	136	] = palabra;
palabra = { PalabraIngles:"	playing chess	", PalabraNativa:"	Jouer aux échecs  	", PalabraTraducida:"	Jugar ajedrez  	"}; unasPalabras[	137	] = palabra;
palabra = { PalabraIngles:"	point 2	", PalabraNativa:"	Point  	", PalabraTraducida:"	Señalar  	"}; unasPalabras[	138	] = palabra;
palabra = { PalabraIngles:"	pour	", PalabraNativa:"	Verser  	", PalabraTraducida:"	Verter  	"}; unasPalabras[	139	] = palabra;
palabra = { PalabraIngles:"	pull	", PalabraNativa:"	Tirez  	", PalabraTraducida:"	Disparar  	"}; unasPalabras[	140	] = palabra;
palabra = { PalabraIngles:"	punch	", PalabraNativa:"	Coup de poing  	", PalabraTraducida:"	Puñetazo  	"}; unasPalabras[	141	] = palabra;
palabra = { PalabraIngles:"	push	", PalabraNativa:"	Pousser  	", PalabraTraducida:"	Empujar  	"}; unasPalabras[	142	] = palabra;
palabra = { PalabraIngles:"	put down 3	", PalabraNativa:"	Poser  	", PalabraTraducida:"	Poner  	"}; unasPalabras[	143	] = palabra;
palabra = { PalabraIngles:"	put on makeup	", PalabraNativa:"	Mettre du maquillage  	", PalabraTraducida:"	Maquillarse  	"}; unasPalabras[	144	] = palabra;
palabra = { PalabraIngles:"	rake the leaves	", PalabraNativa:"	Ratisser les feuilles  	", PalabraTraducida:"	Rastrillar las hojas  	"}; unasPalabras[	145	] = palabra;
palabra = { PalabraIngles:"	read the news	", PalabraNativa:"	Lire les nouvelles  	", PalabraTraducida:"	Leer las noticias  	"}; unasPalabras[	146	] = palabra;
palabra = { PalabraIngles:"	read	", PalabraNativa:"	Lis  	", PalabraTraducida:"	Leer  	"}; unasPalabras[	147	] = palabra;
palabra = { PalabraIngles:"	repair	", PalabraNativa:"	Réparation  	", PalabraTraducida:"	Reparar  	"}; unasPalabras[	148	] = palabra;
palabra = { PalabraIngles:"	ride 1	", PalabraNativa:"	Tour  	", PalabraTraducida:"	Girar  	"}; unasPalabras[	149	] = palabra;
palabra = { PalabraIngles:"	ride	", PalabraNativa:"	Balade  	", PalabraTraducida:"	Pasear  	"}; unasPalabras[	150	] = palabra;
palabra = { PalabraIngles:"	roast 2	", PalabraNativa:"	Rôti  	", PalabraTraducida:"	Asar  	"}; unasPalabras[	151	] = palabra;
palabra = { PalabraIngles:"	roll out	", PalabraNativa:"	Sortir  	", PalabraTraducida:"	Salir  	"}; unasPalabras[	152	] = palabra;
palabra = { PalabraIngles:"	run 3	", PalabraNativa:"	Courir  	", PalabraTraducida:"	Correr  	"}; unasPalabras[	153	] = palabra;
palabra = { PalabraIngles:"	run	", PalabraNativa:"	Courir  	", PalabraTraducida:"	Correr  	"}; unasPalabras[	154	] = palabra;
palabra = { PalabraIngles:"	saute	", PalabraNativa:"	Faire sauter  	", PalabraTraducida:"	Saltear  	"}; unasPalabras[	155	] = palabra;
palabra = { PalabraIngles:"	say	", PalabraNativa:"	Dire  	", PalabraTraducida:"	Decir  	"}; unasPalabras[	156	] = palabra;
palabra = { PalabraIngles:"	scrub the floor	", PalabraNativa:"	Frotter le sol  	", PalabraTraducida:"	Fregar el piso  	"}; unasPalabras[	157	] = palabra;
palabra = { PalabraIngles:"	serve 1 1	", PalabraNativa:"	Servir  	", PalabraTraducida:"	Servir  	"}; unasPalabras[	158	] = palabra;
palabra = { PalabraIngles:"	serve 1	", PalabraNativa:"	Servir  	", PalabraTraducida:"	Servir  	"}; unasPalabras[	159	] = palabra;
palabra = { PalabraIngles:"	sew	", PalabraNativa:"	Coudre  	", PalabraTraducida:"	Coser  	"}; unasPalabras[	160	] = palabra;
palabra = { PalabraIngles:"	shake hands	", PalabraNativa:"	Serrer la main  	", PalabraTraducida:"	Dar la mano  	"}; unasPalabras[	161	] = palabra;
palabra = { PalabraIngles:"	sharing	", PalabraNativa:"	Partage  	", PalabraTraducida:"	Compartir  	"}; unasPalabras[	162	] = palabra;
palabra = { PalabraIngles:"	shoot	", PalabraNativa:"	Tirer  	", PalabraTraducida:"	Tirar  	"}; unasPalabras[	163	] = palabra;
palabra = { PalabraIngles:"	shouting 2	", PalabraNativa:"	Criant  	", PalabraTraducida:"	Gritar  	"}; unasPalabras[	164	] = palabra;
palabra = { PalabraIngles:"	show	", PalabraNativa:"	Spectacle  	", PalabraTraducida:"	Espectáculo  	"}; unasPalabras[	165	] = palabra;
palabra = { PalabraIngles:"	sing	", PalabraNativa:"	Chanter  	", PalabraTraducida:"	Cantar  	"}; unasPalabras[	166	] = palabra;
palabra = { PalabraIngles:"	sit 2	", PalabraNativa:"	Assis  	", PalabraTraducida:"	Sentarse  	"}; unasPalabras[	167	] = palabra;
palabra = { PalabraIngles:"	sit down	", PalabraNativa:"	Asseyez-vous  	", PalabraTraducida:"	Siéntese  	"}; unasPalabras[	168	] = palabra;
palabra = { PalabraIngles:"	sit	", PalabraNativa:"	Asseoir  	", PalabraTraducida:"	Sentar  	"}; unasPalabras[	169	] = palabra;
palabra = { PalabraIngles:"	skateboarding	", PalabraNativa:"	Faire de la planche à roulettes  	", PalabraTraducida:"	Andar en patineta  	"}; unasPalabras[	170	] = palabra;
palabra = { PalabraIngles:"	Ski 1	", PalabraNativa:"	Ski  	", PalabraTraducida:"	Esquiar  	"}; unasPalabras[	171	] = palabra;
palabra = { PalabraIngles:"	skip 1	", PalabraNativa:"	Sauter  	", PalabraTraducida:"	Saltar  	"}; unasPalabras[	172	] = palabra;
palabra = { PalabraIngles:"	sleep	", PalabraNativa:"	Dormir  	", PalabraTraducida:"	Dormir  	"}; unasPalabras[	173	] = palabra;
palabra = { PalabraIngles:"	slice 1	", PalabraNativa:"	Tranche  	", PalabraTraducida:"	Rebanar  	"}; unasPalabras[	174	] = palabra;
palabra = { PalabraIngles:"	slice	", PalabraNativa:"	Tranche  	", PalabraTraducida:"	Rebanar  	"}; unasPalabras[	175	] = palabra;
palabra = { PalabraIngles:"	slip 1	", PalabraNativa:"	Feuillet  	", PalabraTraducida:"	Hoja  	"}; unasPalabras[	176	] = palabra;
palabra = { PalabraIngles:"	smell	", PalabraNativa:"	Odeur  	", PalabraTraducida:"	Oler  	"}; unasPalabras[	177	] = palabra;
palabra = { PalabraIngles:"	snore	", PalabraNativa:"	Ronfler  	", PalabraTraducida:"	Roncar  	"}; unasPalabras[	178	] = palabra;
palabra = { PalabraIngles:"	spell	", PalabraNativa:"	Épeler  	", PalabraTraducida:"	Deletrear  	"}; unasPalabras[	179	] = palabra;
palabra = { PalabraIngles:"	spread	", PalabraNativa:"	Propager  	", PalabraTraducida:"	Untar  	"}; unasPalabras[	180	] = palabra;
palabra = { PalabraIngles:"	squat	", PalabraNativa:"	S'accroupir  	", PalabraTraducida:"	Agacharse  	"}; unasPalabras[	181	] = palabra;
palabra = { PalabraIngles:"	stack	", PalabraNativa:"	Empiler  	", PalabraTraducida:"	Apilar  	"}; unasPalabras[	182	] = palabra;
palabra = { PalabraIngles:"	stand up	", PalabraNativa:"	Se lever  	", PalabraTraducida:"	Levantarse  	"}; unasPalabras[	183	] = palabra;
palabra = { PalabraIngles:"	Stand	", PalabraNativa:"	Supporter  	", PalabraTraducida:"	Soportar  	"}; unasPalabras[	184	] = palabra;
palabra = { PalabraIngles:"	steam	", PalabraNativa:"	Vapeur  	", PalabraTraducida:"	Vapor  	"}; unasPalabras[	185	] = palabra;
palabra = { PalabraIngles:"	stir	", PalabraNativa:"	Remuer  	", PalabraTraducida:"	Revolver  	"}; unasPalabras[	186	] = palabra;
palabra = { PalabraIngles:"	stretch 1	", PalabraNativa:"	S'étirer  	", PalabraTraducida:"	Estirarse  	"}; unasPalabras[	187	] = palabra;
palabra = { PalabraIngles:"	Stretch	", PalabraNativa:"	Étendue  	", PalabraTraducida:"	Extensión  	"}; unasPalabras[	188	] = palabra;
palabra = { PalabraIngles:"	study	", PalabraNativa:"	Étude  	", PalabraTraducida:"	Estudio  	"}; unasPalabras[	189	] = palabra;
palabra = { PalabraIngles:"	Surf in the Internet	", PalabraNativa:"	Surfer sur Internet  	", PalabraTraducida:"	Navegar en Internet  	"}; unasPalabras[	190	] = palabra;
palabra = { PalabraIngles:"	surf the net	", PalabraNativa:"	Naviguer sur Internet  	", PalabraTraducida:"	Navegar en Internet  	"}; unasPalabras[	191	] = palabra;
palabra = { PalabraIngles:"	surfing 1	", PalabraNativa:"	Surf  	", PalabraTraducida:"	Surf  	"}; unasPalabras[	192	] = palabra;
palabra = { PalabraIngles:"	sweep the floor	", PalabraNativa:"	Balayez le sol  	", PalabraTraducida:"	Barrer el suelo  	"}; unasPalabras[	193	] = palabra;
palabra = { PalabraIngles:"	swimming 3	", PalabraNativa:"	Natation  	", PalabraTraducida:"	Nadar  	"}; unasPalabras[	194	] = palabra;
palabra = { PalabraIngles:"	take a bath	", PalabraNativa:"	Prendre un bain  	", PalabraTraducida:"	Tomar un baño  	"}; unasPalabras[	195	] = palabra;
palabra = { PalabraIngles:"	take a shower	", PalabraNativa:"	Prendre une douche  	", PalabraTraducida:"	Tomar una ducha  	"}; unasPalabras[	196	] = palabra;
palabra = { PalabraIngles:"	take a taxi	", PalabraNativa:"	Prendre un taxi  	", PalabraTraducida:"	Tomar un taxi  	"}; unasPalabras[	197	] = palabra;
palabra = { PalabraIngles:"	take out the rubbish 1	", PalabraNativa:"	Sortir les ordures  	", PalabraTraducida:"	Sacar la basura  	"}; unasPalabras[	198	] = palabra;
palabra = { PalabraIngles:"	take out the rubbish	", PalabraNativa:"	Sortir les poubelles  	", PalabraTraducida:"	Sacar la basura  	"}; unasPalabras[	199	] = palabra;
palabra = { PalabraIngles:"	take pictures	", PalabraNativa:"	Prendre des photos  	", PalabraTraducida:"	Tomar fotos  	"}; unasPalabras[	200	] = palabra;
palabra = { PalabraIngles:"	talk	", PalabraNativa:"	Parler  	", PalabraTraducida:"	Hablar  	"}; unasPalabras[	201	] = palabra;
palabra = { PalabraIngles:"	taste	", PalabraNativa:"	Goût  	", PalabraTraducida:"	Sabor  	"}; unasPalabras[	202	] = palabra;
palabra = { PalabraIngles:"	teach	", PalabraNativa:"	Apprendre  	", PalabraTraducida:"	Aprender  	"}; unasPalabras[	203	] = palabra;
palabra = { PalabraIngles:"	think 1	", PalabraNativa:"	Pense que  	", PalabraTraducida:"	Pensar que  	"}; unasPalabras[	204	] = palabra;
palabra = { PalabraIngles:"	think	", PalabraNativa:"	Pense  	", PalabraTraducida:"	Pensar  	"}; unasPalabras[	205	] = palabra;
palabra = { PalabraIngles:"	throw 1	", PalabraNativa:"	Lancer  	", PalabraTraducida:"	Lanzar  	"}; unasPalabras[	206	] = palabra;
palabra = { PalabraIngles:"	throw away	", PalabraNativa:"	Jeter  	", PalabraTraducida:"	Tirar  	"}; unasPalabras[	207	] = palabra;
palabra = { PalabraIngles:"	throw	", PalabraNativa:"	Jeter  	", PalabraTraducida:"	Tirar  	"}; unasPalabras[	208	] = palabra;
palabra = { PalabraIngles:"	tighten	", PalabraNativa:"	Serrer  	", PalabraTraducida:"	Abrazar  	"}; unasPalabras[	209	] = palabra;
palabra = { PalabraIngles:"	tiptoe 1 1	", PalabraNativa:"	Pointe de pied  	", PalabraTraducida:"	Punta del pie  	"}; unasPalabras[	210	] = palabra;
palabra = { PalabraIngles:"	To have lunch	", PalabraNativa:"	Déjeuner  	", PalabraTraducida:"	Almorzar  	"}; unasPalabras[	211	] = palabra;
palabra = { PalabraIngles:"	touch7esl	", PalabraNativa:"	Touch7esl  	", PalabraTraducida:"	Tocar  	"}; unasPalabras[	212	] = palabra;
palabra = { PalabraIngles:"	Trip	", PalabraNativa:"	Voyage  	", PalabraTraducida:"	Viajar  	"}; unasPalabras[	213	] = palabra;
palabra = { PalabraIngles:"	turn off	", PalabraNativa:"	Éteindre  	", PalabraTraducida:"	Apagar  	"}; unasPalabras[	214	] = palabra;
palabra = { PalabraIngles:"	turn on	", PalabraNativa:"	Allumer  	", PalabraTraducida:"	Encender  	"}; unasPalabras[	215	] = palabra;
palabra = { PalabraIngles:"	Untitled design 6	", PalabraNativa:"	Design sans titre 6  	", PalabraTraducida:"	Diseño sin título 6  	"}; unasPalabras[	216	] = palabra;
palabra = { PalabraIngles:"	vacuum the floor	", PalabraNativa:"	Passer l'aspirateur  	", PalabraTraducida:"	Pasar la aspiradora  	"}; unasPalabras[	217	] = palabra;
palabra = { PalabraIngles:"	vacuum	", PalabraNativa:"	Vide  	", PalabraTraducida:"	Vacío  	"}; unasPalabras[	218	] = palabra;
palabra = { PalabraIngles:"	wait for the bus	", PalabraNativa:"	Attendre le bus  	", PalabraTraducida:"	Esperar el autobús  	"}; unasPalabras[	219	] = palabra;
palabra = { PalabraIngles:"	wait	", PalabraNativa:"	Attendre  	", PalabraTraducida:"	Esperar  	"}; unasPalabras[	220	] = palabra;
palabra = { PalabraIngles:"	wake up	", PalabraNativa:"	Réveillez-vous  	", PalabraTraducida:"	Despertarse  	"}; unasPalabras[	221	] = palabra;
palabra = { PalabraIngles:"	walk 1	", PalabraNativa:"	Marche  	", PalabraTraducida:"	Caminar  	"}; unasPalabras[	222	] = palabra;
palabra = { PalabraIngles:"	walk the dog	", PalabraNativa:"	Promener le chien  	", PalabraTraducida:"	Pasear al perro  	"}; unasPalabras[	223	] = palabra;
palabra = { PalabraIngles:"	walk	", PalabraNativa:"	Marche  	", PalabraTraducida:"	Caminar  	"}; unasPalabras[	224	] = palabra;
palabra = { PalabraIngles:"	wash the car	", PalabraNativa:"	Lave la voiture  	", PalabraTraducida:"	Lavar el auto  	"}; unasPalabras[	225	] = palabra;
palabra = { PalabraIngles:"	wash	", PalabraNativa:"	Lavage  	", PalabraTraducida:"	Lavado  	"}; unasPalabras[	226	] = palabra;
palabra = { PalabraIngles:"	watch TV	", PalabraNativa:"	Regarder la télévision  	", PalabraTraducida:"	Ver televisión  	"}; unasPalabras[	227	] = palabra;
palabra = { PalabraIngles:"	water the plants	", PalabraNativa:"	Arroser les plantes  	", PalabraTraducida:"	Regar las plantas  	"}; unasPalabras[	228	] = palabra;
palabra = { PalabraIngles:"	Wave	", PalabraNativa:"	Vague  	", PalabraTraducida:"	Saludar  	"}; unasPalabras[	229	] = palabra;
palabra = { PalabraIngles:"	weigh out	", PalabraNativa:"	Peser  	", PalabraTraducida:"	Pesar  	"}; unasPalabras[	230	] = palabra;
palabra = { PalabraIngles:"	whip	", PalabraNativa:"	Fouet  	", PalabraTraducida:"	Batir  	"}; unasPalabras[	231	] = palabra;
palabra = { PalabraIngles:"	win	", PalabraNativa:"	Gagner  	", PalabraTraducida:"	Ganar  	"}; unasPalabras[	232	] = palabra;
palabra = { PalabraIngles:"	wipe the table	", PalabraNativa:"	Essuyez la table  	", PalabraTraducida:"	Limpiar la mesa  	"}; unasPalabras[	233	] = palabra;
palabra = { PalabraIngles:"	work	", PalabraNativa:"	Travail  	", PalabraTraducida:"	Trabajar  	"}; unasPalabras[	234	] = palabra;
palabra = { PalabraIngles:"	write 1	", PalabraNativa:"	Écris  	", PalabraTraducida:"	Escribe  	"}; unasPalabras[	235	] = palabra;
palabra = { PalabraIngles:"	write	", PalabraNativa:"	Écrire	", PalabraTraducida:"	Escribir  	"}; unasPalabras[	236	] = palabra;


cantidadPalabras = unasPalabras.length;
}
